#include <stdio.h>
#include <stdlib.h>
#include"PILE.h"
#include"FILE.h"

int main()
{
    printf("\n######################################\n");
    printf(" A1-pile statique 1\n");
    Piles piles;
    printf("question 1\n");
    creepilefs(&piles);
    int del1=depilerfS(&piles);
    int del2=depilerfS(&piles);
    printf("la valeur depiler est %d\n",del2);
    enpilerfS(&piles,1);
    enpilerfS(&piles,2);
    enpilerfS(&piles,3);
    afficherps(&piles);
    int del3=depilerfS(&piles);
    enpilerfS(&piles,4);
    enpilerfS(&piles,5);
    int del4=depilerfS(&piles);
    enpilerfS(&piles,6);
    enpilerfS(&piles,7);
    enpilerfS(&piles,8);
    enpilerfS(&piles,9);
    enpilerfS(&piles,10);
    printf("\nla pile est\n");
    afficherps(&piles);
    int del5 =depilerfS(&piles);
    printf("\nla pile est\n");
    afficherps(&piles);
    int vale=sommets(&piles);
    printf("question 2\n");
    printf("\nle sommet est %d\n",7);
    printf("question 3\n");
    printf("depiler n executer par normarlement 2\n");
    printf("question 4\n");
    printf("enpiler n executer normarlement 3 car la taille du tableau est a 5\n");
    printf("\n######################################\n");
    printf(" A2-pile dymanique 1\n");
    Pile pile;
    printf("question 1\n");
    creepile(&pile);
    int elt1=depiler(&pile);
    int elt2=depiler(&pile);
    enpiler(&pile,1);
    printf("\nla pile est\n");
    afficher(&pile);
    enpiler(&pile,2);
    printf("\nla pile est\n");
    afficher(&pile);
    enpiler(&pile,3);
    printf("la pile est\n");
    afficher(&pile);
    int elt3=depiler(&pile);
    printf("\nla pile est\n");
    afficher(&pile);
    enpiler(&pile,4);
    enpiler(&pile,5);
    printf("\nla pile est\n");
    afficher(&pile);
    int elt4=depiler(&pile);
    printf("\nla pile est\n");
    afficher(&pile);
    enpiler(&pile,6);
    enpiler(&pile,7);
    enpiler(&pile,8);
    printf("\nla pile est\n");
    afficher(&pile);
    enpiler(&pile,9);
    enpiler(&pile,10);
    int elt5=depiler(&pile);
    printf("\nla pile est\n");
    afficher(&pile);
    int val=sommet(&pile);
    printf("question 2\n");
    printf("\nle sommet est %d\n",val);
    printf("question 3\n");
    printf("depiler n executer par normarlement 2\n");
    printf("question 4\n");
    printf("enpiler n executer normarlement 0 fois\n");
    printf("\n######################################\n");
    printf("A3- file stastique\n");
    Files files;
    creefilefs(&files);
    printf("question 1\n");
    int val3=defilerfS(&files);
    int val4=defilerfS(&files);
    printf("la valeur defiler est %d",val3);
    enfilerfS(&files,1);
    enfilerfS(&files,2);
    enfilerfS(&files,3);
    afficherfs(&files);
    int val1=defilerfS(&files);
    enfilerfS(&files,4);
    enfilerfS(&files,5);
    int val2=defilerfS(&files);
    enfilerfS(&files,6);
    enfilerfS(&files,7);
    afficherfs(&files);
    enfilerfS(&files,8);
    enfilerfS(&files,9);
    enfilerfS(&files,10);
    afficherfs(&files);
    int val5=defilerfS(&files);
    afficherfs(&files);
    printf("question 2\n");
    int nbrs2= tete(&files);
    int nbrs1= queu(&files);
    printf("\n la tete est %d\n",nbrs2);
    printf("question 3\n");
    printf("\n la queue est %d\n",7);
    printf("question 4\n");
    printf("depiler n executer par normarlement 2\n");
    printf("question 5\n");
    printf("enpiler n executer normarlement 3 fois\n");
    printf("question 6\n");
    printf( "l'indixe de debut est %d\n",1);
    printf( "l'indixe de fin est %d\n",5);
    printf("\n######################################\n");
    File file;
    creefile(&file);
    printf("A4- file\n");
    printf("question 1\n");
    int nombre1=defilerf(&file);
    int nombre2=defilerf(&file);
    enfilerf(&file,1);
    printf("\nla file est\n");
    afficherf(&file);
    enfilerf(&file,2);
    enfilerf(&file,3);
    printf("\nla file est\n");
    afficherf(&file);
    int nombre3=defilerf(&file);
    printf("\nla file est\n");
    afficherf(&file);
    enfilerf(&file,4);
    enfilerf(&file,5);
    printf("\nla file est\n");
    afficherf(&file);
    int nombre4=defilerf(&file);
    printf("\nla file est\n");
    afficherf(&file);
    enfilerf(&file,6);
    enfilerf(&file,7);
    enfilerf(&file,8);
    enfilerf(&file,9);
    enfilerf(&file,10);
    printf("\nla file est\n");
    afficherf(&file);
    int nombre5=defilerf(&file);
    printf("\nla file est\n");
    afficherf(&file);
    int nbr1=dernier(&file);
    int nbr2=premier(&file);
    printf("question 2\n");
    printf("\n le sommet est %d\n",nbr2);
    printf("question 3\n");
    printf("\n la queue est %d\n",nbr1);
    printf("question 4\n");
    printf("depiler n executer par normarlement 2\n");
    printf("question 5\n");
    printf("enpiler n executer normarlement 0 fois\n");




    //printf("\n l element defiler est %d\n",nombre);
    return 0;
}
